# Generated by Django 4.2.13 on 2024-06-23 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_remove_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
