# Generated by Django 4.2.13 on 2024-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0014_alter_status_name_alter_task_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='task_manager.label'),
        ),
    ]
